const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Touch,
		C3.Plugins.Mouse,
		C3.Plugins.Sprite,
		C3.Behaviors.MoveTo,
		C3.Behaviors.Timer,
		C3.Behaviors.Tween,
		C3.Behaviors.Sin,
		C3.Behaviors.Bullet,
		C3.Behaviors.destroy,
		C3.Plugins.Particles,
		C3.Plugins.Text,
		C3.Plugins.yagames_sdk,
		C3.Behaviors.scrollto,
		C3.Behaviors.Flash,
		C3.Plugins.Keyboard,
		C3.Plugins.TiledBg,
		C3.Plugins.Audio,
		C3.Behaviors.Anchor,
		C3.Plugins.LocalStorage,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Cnds.PickParent,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.System.Cnds.ForEachOrdered,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Exps.loopindex,
		C3.Behaviors.MoveTo.Acts.MoveToObject,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.Sprite.Cnds.PickDistance,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Cnds.PickRandom,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Cnds.OnAnyAnimFinished,
		C3.Plugins.System.Cnds.OnLayoutEnd,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetEffectEnabled,
		C3.Plugins.Particles.Cnds.OnCreated,
		C3.Plugins.Particles.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Plugins.Text.Acts.SetText,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.System.Exps.dt,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Behaviors.Timer.Acts.StopAllTimers,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.BBoxLeft,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Behaviors.Timer.Acts.StopTimer,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Cnds.CompareWidth,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Exps.ImageWidth,
		C3.Plugins.Sprite.Exps.ImageHeight,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Cnds.OnFrameChanged,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.yagames_sdk.Acts.ShowFullscreenAD,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.TiledBg.Cnds.CompareInstanceVar,
		C3.Plugins.TiledBg.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.TiledBg.Cnds.PickChildren,
		C3.Plugins.Text.Acts.TypewriterText,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.Sprite.Acts.SetEffectParam,
		C3.Plugins.Text.Cnds.OnCreated,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Acts.SaveState,
		C3.Plugins.LocalStorage.Acts.ClearStorage,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.yagames_sdk.Cnds.OnFullscreenADOpen,
		C3.Plugins.yagames_sdk.Acts.GameplayAPIStop,
		C3.Plugins.Audio.Acts.SetMuted,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.yagames_sdk.Cnds.OnFullscreenADClose,
		C3.Plugins.yagames_sdk.Cnds.OnAnyRewardedADClose,
		C3.Plugins.yagames_sdk.Cnds.OnAnyRewardedADOpen,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.Plugins.yagames_sdk.Acts.ShowRewardedAD,
		C3.Plugins.yagames_sdk.Cnds.OnRewardedADRewarded,
		C3.Plugins.yagames_sdk.Acts.GameplayAPIStart,
		C3.Plugins.yagames_sdk.Acts.LoadingAPIReady,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.System.Acts.LoadState,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing
	];
};
self.C3_JsPropNameTable = [
	{Тач: 0},
	{Мышь: 0},
	{Занят: 0},
	{Начало: 0},
	{Главный: 0},
	{ЗоныБойцов: 0},
	{ГлавнаяЗонаБойцов: 0},
	{ДвижениеК: 0},
	{Таймер: 0},
	{Твинанимация: 0},
	{Синусоида: 0},
	{Воин: 0},
	{Умножение: 0},
	{СозданнаБойцом: 0},
	{Пуля: 0},
	{DestroyOutside: 0},
	{Дальность: 0},
	{ХП: 0},
	{Босс: 0},
	{Враги: 0},
	{СмертьВрагов: 0},
	{ХПВРАГОВ: 0},
	{Значение: 0},
	{Воротца: 0},
	{Спрайт: 0},
	{Что: 0},
	{Текст: 0},
	{СмертьВоинов: 0},
	{Уничтожающие: 0},
	{ЗначениеСкорости: 0},
	{Оружие: 0},
	{БочкаСБонусом: 0},
	{БонусПолучен: 0},
	{Сундук: 0},
	{Спрайт2: 0},
	{ВоротцаПуль: 0},
	{Количество: 0},
	{Столбец: 0},
	{Ряд: 0},
	{Этот: 0},
	{СпавнерВолны: 0},
	{СпавнерСундука: 0},
	{ЗонаБазы: 0},
	{Анимация: 0},
	{ХПАнимация: 0},
	{Темень: 0},
	{YandexGamesSDK: 0},
	{Поражение: 0},
	{СледитьЗа: 0},
	{Камера: 0},
	{Поражение2: 0},
	{КонецВолны: 0},
	{ЗонаКонцаВолны: 0},
	{Спрайт3: 0},
	{СпавнерБосс: 0},
	{Мигание: 0},
	{Портреты: 0},
	{Осколки: 0},
	{ОсколкиТекст: 0},
	{Золото: 0},
	{ЗолотоТекст: 0},
	{Спрайт5: 0},
	{ПодкладкаОткрытияСундука: 0},
	{Клавиатура: 0},
	{ТОчкаВолны1: 0},
	{ТОчкаВолны2: 0},
	{Позиция: 0},
	{УправляторВолны: 0},
	{Высота: 0},
	{Здания: 0},
	{Стена: 0},
	{ОсколкиСтены: 0},
	{Ширина: 0},
	{Цена: 0},
	{Кнопка: 0},
	{Текст2: 0},
	{Золотишко: 0},
	{Спрайт4: 0},
	{ЗолотоЗначок: 0},
	{ПерсонажиВменю: 0},
	{ОписаниеПрокачки: 0},
	{МожноОткрыть: 0},
	{Открыт: 0},
	{ВыборПерсонажей: 0},
	{ПодкладкаПодПРокачку: 0},
	{КоличествоОсколков: 0},
	{Прокачка: 0},
	{КнопкаПерсонажей: 0},
	{ТочкаКамеры1: 0},
	{ТочкаКамеры2: 0},
	{КнопкаДомой: 0},
	{БОСС: 0},
	{Уровень: 0},
	{ОбозначениеУровней: 0},
	{Ползунок: 0},
	{Какой: 0},
	{БлокДороги: 0},
	{Яма: 0},
	{Вспышка: 0},
	{ЗначениеФейк: 0},
	{СуперВоротцаПуль: 0},
	{Текст3: 0},
	{ХПМакс: 0},
	{БлокираторСуперВорот: 0},
	{УправляторУровнем: 0},
	{ВоротцаЕдиничка: 0},
	{Активно: 0},
	{ВоротцаЕдиничкаСпавнер: 0},
	{СтенаЕдинички: 0},
	{Распылитель: 0},
	{фон: 0},
	{СпавнерВолны2: 0},
	{ЗонаНачалаСпавна: 0},
	{УправляторВрагами: 0},
	{ЗолотоЧастицы: 0},
	{ХПМАКС: 0},
	{ВременныеВоротца: 0},
	{Уничтожающие2: 0},
	{Портал1: 0},
	{Портал2: 0},
	{ПорталВид: 0},
	{СтартУровня: 0},
	{Спрайт8: 0},
	{Спрайт9: 0},
	{Эмблема: 0},
	{Крыло: 0},
	{Спрайт10: 0},
	{Прокач: 0},
	{ПодложкаПОдПрокачку: 0},
	{ПодложкаПОдПрокачку2: 0},
	{ВыборПерсаПолзунок: 0},
	{Спрайт11: 0},
	{Спрайт12: 0},
	{Спрайт13: 0},
	{Биографии: 0},
	{Убит: 0},
	{Спавнер1: 0},
	{СпавнерБоссКликер: 0},
	{Золот: 0},
	{Монетка: 0},
	{Спрайт6: 0},
	{ТекстХП: 0},
	{Тьма: 0},
	{УровеньКликера: 0},
	{СпавнерЗемли: 0},
	{СтолкновениеЧастицы: 0},
	{Цель: 0},
	{Аудио: 0},
	{Якорь: 0},
	{Музыка: 0},
	{Звук: 0},
	{РекламаЗолото: 0},
	{РекламаОсколки: 0},
	{ЛокальноеХранилище: 0},
	{Рука: 0},
	{Спрайт7: 0},
	{ПодкладкаОткрытияСундука2: 0},
	{Тень: 0},
	{Частицы: 0},
	{Препятствия: 0},
	{ИзСундука: 0},
	{Кнопки: 0},
	{АнимацияПрепятствия: 0},
	{Награда: 0},
	{Твердыни: 0},
	{Ворота: 0},
	{СкоростьПеремещениеБойцов: 0},
	{СкоростьВыстрелов: 0},
	{БазовоеЗначениеБонусаОружия: 0},
	{РаундНачался: 0},
	{КонецРаунда: 0},
	{КолчичествоВРагов: 0},
	{ОбщееКоличествоБойцов: 0},
	{ХПБОссаИСундука: 0},
	{Игра: 0},
	{КоличествоБойцов: 0},
	{МаксимумБойцов: 0},
	{МузыкаЗапуск: 0},
	{Меню: 0},
	{РоллКоличестваЗолота: 0},
	{МожноЖать: 0},
	{СостояниеСундука: 0},
	{РоллПерсонажа: 0},
	{Персонаж2: 0},
	{Персонаж3: 0},
	{Персонаж4: 0},
	{Персонаж5: 0},
	{Персонаж6: 0},
	{Персонаж7: 0},
	{Персонаж8: 0},
	{Персонаж9: 0},
	{Персонаж10: 0},
	{ПерсонажОсколки2: 0},
	{ПерсонажОсколки3: 0},
	{ПерсонажОсколки4: 0},
	{ПерсонажОсколки5: 0},
	{ПерсонажОсколки6: 0},
	{ПерсонажОсколки7: 0},
	{ПерсонажОсколки8: 0},
	{ПерсонажОсколки9: 0},
	{ПерсонажОсколки10: 0},
	{СлучайныйРолл: 0},
	{РоллКоличестваОсколков: 0},
	{ОсколкиБонус: 0},
	{МножительЦены: 0},
	{Урон: 0},
	{ХПБазыАктуал: 0},
	{ЗолотоБонус: 0},
	{ВыборПерсонажа: 0},
	{КоличествоБойцовВНАчале: 0},
	{ХПБазыМакс: 0},
	{ЦенаНовыхБойцов: 0},
	{ЦенаЗолота: 0},
	{ЦенаОсколков: 0},
	{КупиУрон: 0},
	{ЦенаУрона: 0},
	{БоссАктиватор: 0},
	{БонусБосса: 0},
	{РукаУказывает: 0},
	{МузыкаЧек: 0},
	{ЗвукЧек: 0},
	{ЗвукЧекБекап: 0},
	{МузыкаЧекБекап: 0},
	{Реклама: 0},
	{Музыка2: 0},
	{Звук2: 0},
	{РекламаОтсчет: 0},
	{РекламаМожно: 0}
];

self.InstanceType = {
	Тач: class extends self.IInstance {},
	Мышь: class extends self.IInstance {},
	ЗоныБойцов: class extends self.ISpriteInstance {},
	ГлавнаяЗонаБойцов: class extends self.ISpriteInstance {},
	Воин: class extends self.ISpriteInstance {},
	Пуля: class extends self.ISpriteInstance {},
	Враги: class extends self.ISpriteInstance {},
	СмертьВрагов: class extends self.IParticlesInstance {},
	ХПВРАГОВ: class extends self.ITextInstance {},
	Воротца: class extends self.ISpriteInstance {},
	Спрайт: class extends self.ISpriteInstance {},
	Текст: class extends self.ITextInstance {},
	СмертьВоинов: class extends self.IParticlesInstance {},
	Уничтожающие: class extends self.ISpriteInstance {},
	Оружие: class extends self.ISpriteInstance {},
	БочкаСБонусом: class extends self.ISpriteInstance {},
	БонусПолучен: class extends self.IParticlesInstance {},
	Сундук: class extends self.ISpriteInstance {},
	Спрайт2: class extends self.ISpriteInstance {},
	ВоротцаПуль: class extends self.ISpriteInstance {},
	СпавнерВолны: class extends self.ISpriteInstance {},
	СпавнерСундука: class extends self.ISpriteInstance {},
	ЗонаБазы: class extends self.ISpriteInstance {},
	ХП: class extends self.ISpriteInstance {},
	ХПАнимация: class extends self.ISpriteInstance {},
	Темень: class extends self.ISpriteInstance {},
	YandexGamesSDK: class extends C3.Plugins.yagames_sdk.Instance {},
	Поражение: class extends self.ITextInstance {},
	Камера: class extends self.ISpriteInstance {},
	Поражение2: class extends self.ITextInstance {},
	КонецВолны: class extends self.ISpriteInstance {},
	ЗонаКонцаВолны: class extends self.ISpriteInstance {},
	Спрайт3: class extends self.ISpriteInstance {},
	СпавнерБосс: class extends self.ISpriteInstance {},
	Портреты: class extends self.ISpriteInstance {},
	Осколки: class extends self.ISpriteInstance {},
	ОсколкиТекст: class extends self.ITextInstance {},
	Золото: class extends self.ISpriteInstance {},
	ЗолотоТекст: class extends self.ITextInstance {},
	Спрайт5: class extends self.ISpriteInstance {},
	ПодкладкаОткрытияСундука: class extends self.ISpriteInstance {},
	Клавиатура: class extends self.IInstance {},
	ТОчкаВолны1: class extends self.ISpriteInstance {},
	ТОчкаВолны2: class extends self.ISpriteInstance {},
	УправляторВолны: class extends self.ISpriteInstance {},
	Здания: class extends self.ISpriteInstance {},
	Стена: class extends self.ISpriteInstance {},
	ОсколкиСтены: class extends self.IParticlesInstance {},
	Кнопка: class extends self.ISpriteInstance {},
	Цена: class extends self.ITextInstance {},
	Текст2: class extends self.ITextInstance {},
	Золотишко: class extends self.ITextInstance {},
	Спрайт4: class extends self.ISpriteInstance {},
	ЗолотоЗначок: class extends self.ISpriteInstance {},
	ПерсонажиВменю: class extends self.ISpriteInstance {},
	ОписаниеПрокачки: class extends self.ITextInstance {},
	ВыборПерсонажей: class extends self.ISpriteInstance {},
	ПодкладкаПодПРокачку: class extends self.ISpriteInstance {},
	Прокачка: class extends self.ISpriteInstance {},
	КнопкаПерсонажей: class extends self.ISpriteInstance {},
	ТочкаКамеры1: class extends self.ISpriteInstance {},
	ТочкаКамеры2: class extends self.ISpriteInstance {},
	КнопкаДомой: class extends self.ISpriteInstance {},
	БОСС: class extends self.ISpriteInstance {},
	ОбозначениеУровней: class extends self.ISpriteInstance {},
	Ползунок: class extends self.ISpriteInstance {},
	БлокДороги: class extends self.ISpriteInstance {},
	Яма: class extends self.ISpriteInstance {},
	Вспышка: class extends self.ISpriteInstance {},
	СуперВоротцаПуль: class extends self.ISpriteInstance {},
	Текст3: class extends self.ITextInstance {},
	БлокираторСуперВорот: class extends self.ISpriteInstance {},
	УправляторУровнем: class extends self.ISpriteInstance {},
	ВоротцаЕдиничка: class extends self.ISpriteInstance {},
	ВоротцаЕдиничкаСпавнер: class extends self.ISpriteInstance {},
	СтенаЕдинички: class extends self.ISpriteInstance {},
	Распылитель: class extends self.ISpriteInstance {},
	фон: class extends self.ISpriteInstance {},
	СпавнерВолны2: class extends self.ISpriteInstance {},
	ЗонаНачалаСпавна: class extends self.ISpriteInstance {},
	УправляторВрагами: class extends self.ISpriteInstance {},
	ЗолотоЧастицы: class extends self.IParticlesInstance {},
	ВременныеВоротца: class extends self.ISpriteInstance {},
	Уничтожающие2: class extends self.ISpriteInstance {},
	Портал1: class extends self.ISpriteInstance {},
	Портал2: class extends self.ISpriteInstance {},
	ПорталВид: class extends self.ISpriteInstance {},
	СтартУровня: class extends self.ISpriteInstance {},
	Спрайт8: class extends self.ISpriteInstance {},
	Спрайт9: class extends self.ISpriteInstance {},
	Эмблема: class extends self.ISpriteInstance {},
	Крыло: class extends self.ISpriteInstance {},
	Спрайт10: class extends self.ISpriteInstance {},
	Прокач: class extends self.ITiledBackgroundInstance {},
	ПодложкаПОдПрокачку: class extends self.ISpriteInstance {},
	ПодложкаПОдПрокачку2: class extends self.ISpriteInstance {},
	ВыборПерсаПолзунок: class extends self.ISpriteInstance {},
	Спрайт11: class extends self.ISpriteInstance {},
	Спрайт12: class extends self.ISpriteInstance {},
	Спрайт13: class extends self.ISpriteInstance {},
	Биографии: class extends self.ITextInstance {},
	Спавнер1: class extends self.ISpriteInstance {},
	СпавнерБоссКликер: class extends self.ISpriteInstance {},
	Золот: class extends self.IParticlesInstance {},
	Монетка: class extends self.ISpriteInstance {},
	Спрайт6: class extends self.ISpriteInstance {},
	ТекстХП: class extends self.ITextInstance {},
	Тьма: class extends self.ITiledBackgroundInstance {},
	УровеньКликера: class extends self.ITextInstance {},
	СпавнерЗемли: class extends self.ISpriteInstance {},
	СтолкновениеЧастицы: class extends self.IParticlesInstance {},
	Цель: class extends self.ITextInstance {},
	Аудио: class extends self.IInstance {},
	Музыка: class extends self.ISpriteInstance {},
	Звук: class extends self.ISpriteInstance {},
	РекламаЗолото: class extends self.ISpriteInstance {},
	РекламаОсколки: class extends self.ISpriteInstance {},
	КоличествоОсколков: class extends self.ITextInstance {},
	ЛокальноеХранилище: class extends self.IInstance {},
	Рука: class extends self.ISpriteInstance {},
	Спрайт7: class extends self.ISpriteInstance {},
	ПодкладкаОткрытияСундука2: class extends self.ISpriteInstance {},
	Тень: class extends self.ISpriteInstance {},
	Частицы: class extends self.IParticlesInstance {},
	Препятствия: class extends self.ISpriteInstance {},
	ИзСундука: class extends self.ISpriteInstance {},
	Кнопки: class extends self.ISpriteInstance {},
	АнимацияПрепятствия: class extends self.ISpriteInstance {},
	Награда: class extends self.ISpriteInstance {},
	Твердыни: class extends self.ISpriteInstance {},
	Ворота: class extends self.ISpriteInstance {}
}